version: '3'
services:
  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile-rest-tests
    command: bash -c "while true; do sleep 1; done"
    environment:
      - SERVER_NAME=${DOMAIN}
      - FIRST_SUPERUSER={{cookiecutter.first_superuser}}
      - FIRST_SUPERUSER_PASSWORD={{cookiecutter.first_superuser_password}}
