version: '3'
services:
  db:
    volumes:
      - 'app-db-data:/var/lib/postgresql/data/pgdata'
  pgadmin:
    deploy:
      labels:
        - "traefik.frontend.rule=Host:pgadmin.${DOMAIN}"
        - "traefik.enable=true"
        - "traefik.port=5050"
        - "traefik.tags=${TRAEFIK_PUBLIC_TAG}"
        - "traefik.docker.network={{cookiecutter.traefik_public_network}}"
        # Traefik service that listens to HTTP
        - "traefik.redirectorservice.frontend.entryPoints=http"
        - "traefik.redirectorservice.frontend.redirect.entryPoint=https"
        # Traefik service that listens to HTTPS
        - "traefik.webservice.frontend.entryPoints=https"
    networks:
      - {{cookiecutter.traefik_public_network}}
      - default
  swagger-ui:
    deploy:
      labels:
      - "traefik.frontend.rule=PathPrefixStrip:/swagger/"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.tags=${TRAEFIK_TAG}"
    environment:
      - API_URL=https://${DOMAIN}/api/v1/swagger/
  proxy:
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --web
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.frontend.rule=Host:${DOMAIN}"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.tags=${TRAEFIK_PUBLIC_TAG}"
        - "traefik.docker.network={{cookiecutter.traefik_public_network}}"
        # Traefik service that listens to HTTP
        - "traefik.redirectorservice.frontend.entryPoints=http"
        - "traefik.redirectorservice.frontend.redirect.entryPoint=https"
        # Traefik service that listens to HTTPS
        - "traefik.webservice.frontend.entryPoints=https"
    networks:
      - {{cookiecutter.traefik_public_network}}
      - default
  flower:
    deploy:
      labels:
        - "traefik.frontend.rule=Host:flower.${DOMAIN}"
        - "traefik.enable=true"
        - "traefik.port=5555"
        - "traefik.tags=${TRAEFIK_PUBLIC_TAG}"
        - "traefik.docker.network={{cookiecutter.traefik_public_network}}"
        # Traefik service that listens to HTTP
        - "traefik.redirectorservice.frontend.entryPoints=http"
        - "traefik.redirectorservice.frontend.redirect.entryPoint=https"
        # Traefik service that listens to HTTPS
        - "traefik.webservice.frontend.entryPoints=https"
    networks:
      - {{cookiecutter.traefik_public_network}}
      - default
  backend:
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefix:/api"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.tags=${TRAEFIK_TAG}"
  frontend:
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.tags=${TRAEFIK_TAG}"

volumes:
  app-db-data: {}

networks:
  {{cookiecutter.traefik_public_network}}:
    external: true
