version: '3'
services:
  db:
    image: 'postgres:10'
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: {{cookiecutter.postgres_password}}
      PGDATA: /var/lib/postgresql/data/pgdata
  queue:
    image: 'rabbitmq:3'
  backend:
    depends_on: 
      - db
    environment:
      - SERVER_NAME=${DOMAIN}
      - SECRET_KEY={{cookiecutter.secret_key}}
      - SENTRY_DSN={{cookiecutter.sentry_dsn}}
      - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}
      - FIRST_SUPERUSER={{cookiecutter.first_superuser}}
      - FIRST_SUPERUSER_PASSWORD={{cookiecutter.first_superuser_password}}
  celeryworker:
    depends_on: 
      - db
      - queue
    environment:
      - SENTRY_DSN={{cookiecutter.sentry_dsn}}
      - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}
      - FIRST_SUPERUSER={{cookiecutter.first_superuser}}
      - FIRST_SUPERUSER_PASSWORD={{cookiecutter.first_superuser_password}}
  frontend:
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.tags={{cookiecutter.traefik_constraint_tag}}"
