version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
  celeryworker:
    build:
      context: ./backend
      dockerfile: celeryworker.dockerfile
  frontend:
    build: 
      context: ./frontend
      args:
          env: ${ENV-prod}
