version: '3'
services:
  pgadmin:
    image: fenglc/pgadmin4
    depends_on:
      - db
    environment:
      - DEFAULT_USER={{cookiecutter.pgadmin_default_user}}
      - DEFAULT_PASSWORD={{cookiecutter.pgadmin_default_user_password}}
  swagger-ui:
    image: swaggerapi/swagger-ui
  proxy:
    image: traefik:v1.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flower:
    image: totem/celery-flower-docker
    environment:
      - FLOWER_BASIC_AUTH={{cookiecutter.flower_auth}}
