version: '3'
services:
  db:
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: {{cookiecutter.postgres_password}}
      PGDATA: /var/lib/postgresql/data/pgdata
  backend:
    environment:
      - SERVER_NAME=${DOMAIN}
      - SECRET_KEY={{cookiecutter.secret_key}}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SENTRY_DSN={{cookiecutter.sentry_dsn}}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FIRST_SUPERUSER={{cookiecutter.first_superuser}}
      - FIRST_SUPERUSER_PASSWORD={{cookiecutter.first_superuser_password}}
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
  celeryworker:
    environment:
      - SENTRY_DSN={{cookiecutter.sentry_dsn}}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FIRST_SUPERUSER={{cookiecutter.first_superuser}}
      - FIRST_SUPERUSER_PASSWORD={{cookiecutter.first_superuser_password}}
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
